spring:
  application:
    name: moviefinder
  
  r2dbc:
    url: r2dbc:h2:mem:///moviedb?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  
  sql:
    init:
      mode: always
      platform: h2

logging:
  level:
    com.moviefinder: DEBUG
    org.springframework.r2dbc: DEBUG
    io.r2dbc.h2: DEBUG

server:
  port: 8080
